version: '3.8'

services:
  backend:
    image: 'docker-spring-boot-posgres:latest'
    ports:
      - "8085:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/spring_booking
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: spring_booking
    ports:
      - "5432:5432"  
    volumes:
      - postgres_data:/var/lib/postgresql/data
  volumes:
    postgres_data: